### ISSUE TITLE
利用logging.level.xx.xx=trace配置日志级别时，北极星日志配置失效

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#1189]
**Describe the bug**
利用logging.level.xx.xx=trace配置日志级别时，北极星日志配置失效。polaris-java的日志都打印在控制台。

**To Reproduce**
在 bootstrap.yml 或者 application.yml 中添加如下配置即可实现。
```yaml
logging:
  level:
    com.tencent.cloud: debug
```

**Expected behavior**
自定义配置，不影响北极星的日志输出配置

**Environment**
- Version: 1.12.3-Hoxton.SR12

**Additional context**
无。
