### ISSUE TITLE
监控数据上报-主动推动方式配置不生效

### ISSUE THREAD

**Issue by kkw-wang** [Tencent/spring-cloud-tencent#1208]
**Describe the bug**
按照官方文档设置监控数据主动上报并没有生效

**To Reproduce**
使用的依赖及版本：
```
         <!-- 版本管理 -->
        <spring.cloud.tencent.version>1.12.4-2022.0.4</spring.cloud.tencent.version>
        <spring.cloud.version>2022.0.4</spring.cloud.version>
        <spring.framework.version>6.0.11</spring.framework.version>
        <spring-boot.version>3.1.2</spring-boot.version>
        <lombok.version>1.18.20</lombok.version>
        <feign-httpclient.version>13.1</feign-httpclient.version>
```
配置文件：
```spring:
  application:
    name: demo-gateway
  cloud:
    polaris:
      address: grpc://x.x.x.x:8091 # 必填
      namespace: default # 全局 namespace 参数
      stat:
        enabled: true
        pushgateway:
          enabled: true # 开启监控数据推送
          address: x.x.x.x:9091 # 推送地址
          push-interval: 3000 # 推送间隔，单位ms
    tencent:
      # 开启路由监控
      rpc-enhancement:
        enabled: true
        reporter:
          enabled: true
```
**Expected behavior**
访问服务在北极星的控制台能看到服务请求数等相关数据

**补充**
PolarisStatProperties.class的属性是能够注入成功的，但是并没有调用com.tencent.cloud.rpc.enhancement.stat.config.StatConfigModifier#modify这个方法改变监控相关配置，
使用的依旧是默认配置文件：com/tencent/cloud/spring-cloud-starter-tencent-all/1.12.4-2022.0.4/spring-cloud-starter-tencent-all-1.12.4-2022.0.4-sources.jar!/conf/default-config.yml
临时解决方法是新建一个配置文件polaris.yml
```
global:
  statReporter:
    #描述: 是否启用上报
    enable: true
    plugin:
      prometheus:
        #描述: 设置 prometheus 指标上报模式
        #类型:string
        #默认值:pull
        #范围:pull|push
        type: push
```
