### ISSUE TITLE
💡  Who is Using Spring Cloud Tencent

### ISSUE THREAD

**Issue by ranchowang** [Tencent/spring-cloud-tencent#200]
## Who is using Spring Cloud Tencent

Thank everyone for choosing Spring Cloud Tencent. We created this issue to collect use cases so we can drive the Spring Cloud Tencent community to evolve in the right direction. We expect you to submit a comment on this issue to include the following information:

```yaml
Company: ......
Product:  ......
Phase: Evaluation / Development / Test / Production
Proposal: ......
```

## 谁在使用北极星

感谢您选择 Spring Cloud Tencent。我们创建这个 Issue 来收集 Spring Cloud Tencent 的使用案例，帮助 Spring Cloud Tencent 社区向正确的方向演进，期待大家在 Issue 下面添加 Comment，Comment 示例如下所示：

```yaml
公司：......
产品：......
阶段：评估 / 开发 / 测试 / 生产
建议：......
```
