### ISSUE TITLE
Add non-explicit service name configuration support in SpringCloudGateway

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#22]
**What is the feature you want to add?**

I want non-explicit service name configuration support in SpringCloudGateway. See [The DiscoveryClient Route Definition Locator](https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-discoveryclient-route-definition-locator).

**Why do you want to add this feature?**

When using configuration like this:
```yaml
spring:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
          'predicates[0]':
            name: Path
            args:
              pattern: "'/'+serviceId+'/**'"
          'filters[0]':
            name: RewritePath
            args:
              regexp: '''/'' + serviceId + ''/(?<remaining>.*)'''
              replacement: '''/$\{remaining}'''
```
"404 Not Found" error will be thrown.

**How to implement this feature?**

Implement method of "com.tencent.cloud.polaris.discovery.PolarisServiceDiscovery#getServices"

**Additional context**

Maybe [polaris-java](https://github.com/polarismesh/polaris-java) should be updated first.
