### ISSUE TITLE
熔断功能优化

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#297]
sct 这里的上报异常，可能需要考虑下，应该不是所有的5xx错误都认为是调用失败，是不是可以先直接设置网络相关的错误才上报RetFail

_Originally posted by @chuntaojun in https://github.com/Tencent/spring-cloud-tencent/pull/272#discussion_r905687448_

**Comment by misselvexu** [comment]
## Some Ideas.
### Which scenarios require fusing
- Network exceptions
- Service call internal exceptions

### Solutions
- Configurable, the application itself to configure the Http exception status code

```yaml
spring:
  cloud:
    polaris:
      circuitbreaker:
        include-http-codes:
          - 502
          - 503
          - 504
```

- Provide fuse judgment `SPI` interface
