### ISSUE TITLE
可以手动配置router的失败降级策略吗

### ISSUE THREAD

**Issue by VVFtang** [Tencent/spring-cloud-tencent#615]
我看MetadataRouter的默认FailOverType是all，请问可以在哪里修改此配置

**Comment by lepdou** [comment]
@VVFtang 
1. 请求粒度可以参考这个类 [FeatureEnvRouterRequestInterceptor](https://github.com/Tencent/spring-cloud-tencent/blob/2021.0/spring-cloud-tencent-plugin-starters/spring-cloud-tencent-featureenv-plugin/src/main/java/com/tencent/cloud/plugin/featureenv/FeatureEnvRouterRequestInterceptor.java#L63)

2. 全局配置文件的话，目前得在 resources/polaris.yml 里配置

```
consumer:
  serviceRouter:
    plugin:
      metadataRouter:
        #描述: 元数据路由降级策略。none(不降级), all(降级返回所有的节点), others(降级返回其他KEY的节点)
        metadataFailOverType: all
```

北极星所有默认的配置都在这个文件里 [default-config.yml](https://github.com/polarismesh/polaris-java/blob/main/polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml)

这个文件的配置都可以在resources/polaris.yml 覆盖
