### ISSUE TITLE
local-file-root-path 参数设置不生效。

### ISSUE THREAD

**Issue by herodotus-ecosystem** [Tencent/spring-cloud-tencent#753]
## 环境

- Java 17 （liberica openjdk）
- Spring Boot 3.0.0
- Spring Cloud 2022.0.0-RC2
- Spring Cloud Tencent 1.8.1-2022.0.0-RC2
- Docker polarismesh/polaris-server-standalone (latest)
- Idea

## 问题

使用 spring cloud tencent 做服务发现和配置中心。在 polaris 中配置完成相关配置后，在本地 idea中启动服务，运行正常。

相关服务停止之后，会在本地工程中新建一个目录 `./polaris/backup/config` 里面存储了配置和锁定等数据。因 polarismesh/polaris-server-standalone 不支持持久化，存储在本地也可以理解。

我想更改这个config的存放目录，而不是每次都将配置放置在默认的 `./polaris/backup/config` 。因此，我就在服务的 bootstrap.yml 中增加了配置 `local-file-root-path` ，以为这个配置是可以更改config的目录的，具体配置片段如下

```
    polaris:
      address: grpc://@tencent.polaris.server-addr@
      namespace: @tencent.polaris.namespace@
      service: ${spring.application.name}
      local-ip-address: ${spring.cloud.client.ip-address}
      config:
        local-file-root-path: ./configurations/configs/tencent/backup/config
        groups:
          - name: @profile@
            files:
              - herodotus-cloud-environment.yaml
```

但是 `local-file-root-path` 这个配置完成之后并不生效，本地配置仍旧会放置在 `./polaris/backup/config`，日志中输出的信息也是指向 这个目录 `./polaris/backup/config`

![image](https://user-images.githubusercontent.com/11025512/204544654-62c2df83-7aae-4226-8e55-40b54100f8e9.png)

![image](https://user-images.githubusercontent.com/11025512/204544576-5d6d8188-622a-4b26-81c8-4ff5dda5d134.png)

我的问题是：是我对 local-file-root-path 理解有误，不是我理解的用法。还是说确实是不生效。

**Comment by lepdou** [comment]
@herodotus-cloud 

>第一个问题： 相关服务停止之后，会在本地工程中新建一个目录 ./polaris/backup/config 里面存储了配置和锁定等数据。因 polarismesh/polaris-server-standalone 不支持持久化，存储在本地也可以理解。

答：首先 standalone 是北极星服务端的部署模式，跟客户端的 ./polaris/backup/config 缓存是两码事儿。客户端 ./polaris/backup/config 缓存主要是为了当北极星服务端挂了之后，可以读取本地缓存。

> 第二个问题：local-file-root-path 配置不生效问题

答：首先 local-file-root-path 是用于配置中心本地开发模式时，指定读取本地的配置文件目录。本地开发模式主要用于不想连北极星服务端读取配置，而是直接从本地磁盘读取配置文件，用于例如在飞机上这种没有网络，或者为了开发者之间互相隔离的场景。不是用于指定本地的缓存目录。
可以参考文档。[本地开发模式](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E8%87%AA180-%E7%89%88%E6%9C%AC)

三、如何更给本地配置文件的缓存路径

目前可以在 resources/polaris.yml 文件里配置。因为 polaris sdk 里定义的可配置项很多，现在只把一些非常常用的配置在 sct 层面设计了，然后覆盖 polaris sdk 的配置。

```
config:
  # 类型转化缓存的key数量
  propertiesValueCacheSize: 100
  # 类型转化缓存的过期时间，默认为1分钟
  propertiesValueExpireTime: 60000
  # 连接器配置，默认为北极星服务端
  serverConnector:
   # 本地缓存目录
    persistDir: /Users/lepdou/Documents/xxx 
    #描述: 配置文件写盘失败的最大重试次数
    persistMaxWriteRetry: 1
    #描述: 配置文件从磁盘读取失败的最大重试次数
    persistMaxReadRetry: 0
    #描述: 缓存读写磁盘的重试间隔
    persistRetryInterval: 500ms
    #描述: polaris server获取配置文件失败是否允许回退到本地配置文件开关
    fallbackToLocalCache: true
```
